# This file is automatically @generated by Poetry 1.5.4 and should not be changed by hand.
package = []

[metadata]
lock-version = "2.0"
python-versions = ">=3.10.0,<3.12"
content-hash = "????????????????????"